service: todo-serverless
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-sns

custom:
  stage: ${opt:stage, "dev"}
  secrets: ${file(secrets.json)}
  serverless-offline:
    httpPort: 4000
  serverless-offline-sns:
    port: 4002 # a free port for the sns server to run on
    debug: false
    accountId: ${self:custom.secrets.SNS_ACCOUNT}

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  deploymentBucket:
    name: todo-serverless-aws-lambda.${self:provider.region}.deploys.${self:custom.stage}
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  environment:
    APP_ENV: ${self:custom.secrets.APP_ENV}
    SNS_REGION: ${self:custom.secrets.SNS_REGION}
    SNS_KEY: ${self:custom.secrets.SNS_KEY}
    SNS_SECRET: ${self:custom.secrets.SNS_SECRET}
    SNS_ACCOUNT: ${self:custom.secrets.SNS_ACCOUNT}
    STAGE: ${self:custom.stage}

functions:
  hello:
    handler: handlers.hello
    events:
      - httpApi:
          path: '/hello'
          method: get

  getTodo:
    handler: handlers.getTodo
    events:
      - httpApi:
          path: '/todo'
          method: get
  
  dispatch:
    handler: handlers.dispatch
    events:
      - httpApi:
          path: '/dispatch'
          method: get
  
  consume:
    handler: handlers.consume
    description: Consume MyTopic  - Subscriber
    events:
      - sns: ${self:custom.stage}-MyTopic
