service: todo-serverless
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, "dev"}
  secrets: ${file(secrets.json)}
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  deploymentBucket:
    name: todo-serverless-aws-lambda.${self:provider.region}.deploys.${self:custom.stage}
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  environment:
    APP_ENV: ${self:custom.secrets.APP_ENV}
    
functions:
  hello:
    handler: handlers.hello
    events:
      - http:
          path: '/hello'
          method: get
