name: Deploy production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: deploy production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: create env file
      run: |
            cat > secrets.json << EOF
            {
              "APP_ENV": "production"
            }
            EOF
    - run: cat secrets.json
    
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}